package com.haidousm.rona.client.gui;

import com.haidousm.rona.client.client.Client;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;

public class ConnectPage extends JFrame {
    private JLabel welcomeMessage;
    private JPanel mainPanel;
    private JTextField ipAddressTextField;
    private JTextField portNumberTextField;
    private JButton connectButton;

    public ConnectPage(String title) {
        super(title);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setContentPane(mainPanel);
        this.pack();
        setLocationRelativeTo(null);

        connectButton.addActionListener(e -> {
            handleConnectClicked();
        });
    }

    private void handleConnectClicked() {
        String ipAddress = ipAddressTextField.getText();
        String portNumber = portNumberTextField.getText();
        if (ipAddress.isEmpty() || portNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter IP address and port number.");
        } else {
            int port = Integer.parseInt(portNumber);
            if (port < 0 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Port number must be between 0 and 65535.");
            }
            try {
                Client client = new Client(ipAddress, port);
                JFrame AuthGUI = new AuthenticatePage("Rona", client);
                AuthGUI.setVisible(true);
                this.dispose();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Failed to connect to server.");
            }

        }
    }

    @Override
    public Insets getInsets() {
        return new Insets(10, 10, 10, 10);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        welcomeMessage = new JLabel();
        welcomeMessage.setText("Welcome To Rona");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        mainPanel.add(welcomeMessage, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("IP Address");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        ipAddressTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(ipAddressTextField, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Port Number");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label2, gbc);
        portNumberTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(portNumberTextField, gbc);
        connectButton = new JButton();
        connectButton.setText("Connect");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(connectButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
